# Generated by Django 6.1 on 2026-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioEchoesEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=255)),
                ('episode_name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('broadcast_date', models.CharField(blank=True, max_length=50, null=True)),
                ('episode_length', models.CharField(blank=True, max_length=50, null=True)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('play_link', models.URLField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('scraped_url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Radio Echoes Episodes',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
